getting it working

diff --git a/bin/rolling-reboot b/bin/rolling-reboot
--- a/bin/rolling-reboot
+++ b/bin/rolling-reboot
@@ -30,10 +30,9 @@ main() {
                 if test "$COUNT_REBOOT" -lt "$MAX_REBOOT"
                 then
                     COUNT_REBOOT=$((COUNT_REBOOT+1))
-                    ssh "$HOST" /sbin/reboot -f 1>&2
-                    echo "$HOST"
+                    ssh -o ConnectTimeout=3 "$HOST" /sbin/shutdown -r now 1>&2 && echo "$HOST" || echo 1>&2 "WARNING: Unknown state for $HOST because SSH failed."
                 else
-                    echo 1>&2 "Rebooted $COUNT_REBOOT/$MAX_REBOOT nodes, exiting."
+                    echo 1>&2 "Attempted reboot on $COUNT_REBOOT/$MAX_REBOOT nodes, exiting."
                     exit
                 fi
             else
@@ -44,7 +43,7 @@ main() {
         fi
     done
 
-    echo 1>&2 "Rebooted $COUNT_REBOOT/$MAX_REBOOT nodes, exiting."
+    echo 1>&2 "Attempted reboot on $COUNT_REBOOT/$MAX_REBOOT nodes, exiting."
     exit
 }
 
