try to use `reboot -f` again

diff --git a/bin/rolling-reboot b/bin/rolling-reboot
--- a/bin/rolling-reboot
+++ b/bin/rolling-reboot
@@ -30,7 +30,7 @@ main() {
                 if test "$COUNT_REBOOT" -lt "$MAX_REBOOT"
                 then
                     COUNT_REBOOT=$((COUNT_REBOOT+1))
-                    ssh -o ConnectTimeout=3 "$HOST" /sbin/shutdown -r now 1>&2 && echo "$HOST" || echo 1>&2 "WARNING: Unknown state for $HOST because SSH failed."
+                    gtimeout 5 ssh -o ConnectTimeout=3 "$HOST" /sbin/reboot -f 1>&2 && echo "$HOST" || echo 1>&2 "WARNING: Unknown state for $HOST because SSH failed."
                 else
                     echo 1>&2 "Attempted reboot on $COUNT_REBOOT/$MAX_REBOOT nodes, exiting."
                     exit
